---
title: ""
---

## ¿Quién puede participar en el semillero?

- Cualquier persona que tenga interés en aprender a utilizar los lenguajes de programación R y Python para análisis de datos. **El semillero es totalmente abierto y no tiene ningún costo.**

## Propósitos del semillero  

- Fomentar la discusión de temas relacionados con estadística computacional aplicada .
- Promover la formulación y ejecución de proyectos de investigación con énfasis en métodos estadísticos aplicados.
- Estimular el uso de herramientas tecnológicas que viabilicen el ejercicio académico y profesional.
- Impulsar la utilización de herramientas de código abierto ([software libre](https://en.wikipedia.org/wiki/Free_software)) para ejecutar análisis estadístico.
- Fomentar la sinergía científica entre estudiantes, docentes y comunidad en general.

## Horario

- **Lugar:** reuniones virtuales.
- **Canal de Youtube:** [RPyCol- @rpycol](https://www.youtube.com/@rpycol)
- **Hora:** sábados 10:00 am a 12:00 pm - Colombia.

## Dirección del semillero

- [Luis Gabriel González Herrera](https://scholar.google.es/citations?user=6H65sOoAAAAJ&hl=es)
- [Edimer David Jaramillo](https://edimer.netlify.app/)  

## Contacto

- Escríbenos a [semillerorpy@gmail.com]()

<center> <p>Página web construida con Quarto - <a href="https://github.com/web-edimer/unal-semilleror-facca.github.io">Código fuente en Github.</a></p></center>