---
title: "Actividades 2021-01"
---

| Tema | Ejemplo *HTML*| Código *.Rmd* |
| :----- | :-----: | :-------: |
| [1. Repaso R-Markdown  y Tidyverse](/Actividades/2021_01/01_repaso.html) | [Ejemplo 01 - R Markdown](/Actividades/2021_01/01-ejemplo-rmarkdown-semillero.html)  | [Descargar](/Actividades/2021_01/documents_rmd/01-semillero.Rmd) |
| [2. Novedades en el tidyverse y bibliotecas auxiliares](/Actividades/2021_01/02-Tidyverse.html) | [Ejemplo 02 - `tidyverse`](https://rpubs.com/Edimer/754957) | [Descargar](/Actividades/2021_01/documents_rmd/02-tidyverse.Rmd) |
| [3. Visualización con R: parte 1](/Actividades/2021_01/03_ggplot2_p1.html) | [Ejemplo 03 - `tidyverse`](https://rpubs.com/Edimer/757689) | [Descargar](/Actividades/2021_01/documents_rmd/03-mas-graficos.Rmd)  |
| [4. Visualización con R: parte 2](/Actividades/2021_01/04-Visualization-p2.html) | [Ejemplo 04 - `tidyverse`](https://rpubs.com/Edimer/757689)  | [Descargar](/Actividades/2021_01/documents_rmd/03-mas-graficos.Rmd) |
| [5. Tableros: flexdashboard 1](/Actividades/2021_01/05-Dashboard-1.html) | [Ejemplo 05 - Dashboard 1](https://rpubs.com/Edimer/764924) | [Descargar](/Actividades/2021_01/documents_rmd/tablero1.Rmd) |
| [6. Tableros: flexdashboard 2](/Actividades/2021_01/06-Dashboard-2.html) | [Ejemplo 06 - Dashboard 2]() | [Descargar](/Actividades/2021_01/documents_rmd/tablero2.Rmd) |
| [7. Shiny: Introducción](/Actividades/2021_01/07-Intro-Shiny.html) |  | |
| [8. Shiny + flexdashboard]() |  | |

# Guías

| Guía | Descripción |
| :----- | :----- |
| [Guía 1. Actualizar versión de R (Windows)](/Actividades/2021_01/guide01.html) | Guía para actualización de versión de R en sistema operativo Windows, haciendo uso de la biblioteca `installr`. |
| [Guía 2. Actualizar bibliotecas de R con RStudio](/Actividades/2021_01/guide02.html) | Guía para actualización de bibliotecas de R a través de RStudio. |
