---
title: "Actividades"
---

### Temario general 2019-01
  
  - [0. Bienvenida](/Actividades/0_Bienvenida.html)
  - [1. Introducción a R y RStudio](/Actividades/1_Intro.html)
      - [Ecosistema R Markdown (I)](/Actividades/1_RMarkdown.html)
      - [Ecosistema R Markdown (II)](/Actividades/1.2_RMarkdown.html)
      - [Actividad práctica 1](/Actividades/Actividad1.html)
      - [Guías - Tutoriales](/Actividades/GuiasR.html)
  - [2. El mundo de R + `tidyverse` I](/Actividades/2_MundoR.html)
      - [Ejemplo práctico grupo lunes.](https://rpubs.com/Edimer/477135)
          - [Archivo .Rmd](https://github.com/unal-semilleroR-FacCA/unal-semilleror-facca.github.io/blob/master/Actividades/Indice_Educativo.Rmd)
          - [Archivo .css](https://github.com/unal-semilleroR-FacCA/unal-semilleror-facca.github.io/blob/master/Actividades/estiloSemillero.css)
      - [Ejemplo práctico grupo martes.](https://rpubs.com/Edimer/477747)
          - [Archivo .Rmd](https://github.com/unal-semilleroR-FacCA/unal-semilleror-facca.github.io/blob/master/Actividades/Nutricion.Rmd)
          - [Archivo .css](https://github.com/unal-semilleroR-FacCA/unal-semilleror-facca.github.io/blob/master/Actividades/estiloSemillero.css)
  - [3. El mundo de R + `tidyverse` II](/Actividades/2_MundoR_tidy.html)      
      - [Ejemplo práctico grupo lunes - ICFES 2017_02]()
          - [Archivo .Rmd]()
      - [Ejemplo práctico grupo martes - ICFES 2018_02](https://rpubs.com/Edimer/482725)
          - [Datos iniciales en formato .Rdata](/Actividades/Icfes_201802.Rdata)
          - [Datos depurados en formato .Rdata](/Actividades/Icfes_depurada.Rdata)
          - [Archivo .Rmd]()
  
### Dinámica del semillero

  - Temas principales 2019-01:
      - Introducción a R y RStudio.
      - Ecosistema R Markdown.
      - Manejo y procesamiento de bases de datos con R.
      - Estadística descriptiva con R.
      - Visualización de datos con R.
  - Con ambos grupos (lunes y martes) se abordarán los mismos temas.
  - Todas las sesiones serán asistidas por la dirección del semillero.
  - Cada sesión contará con actividades desarrolladas por los participantes.