---
title: "Actividades 2019-02"
---

  - Temas principales:
      - Estadística y Machine Learning
      - Visualización de datos: fundamentos prácticos
          - Visualización estática
          - Visualización interactiva
      - Investigación reproducible con `R Markdown`
          - Presenstaciones
          - Documentos *pdf*
          - Tableros de datos (*dashboard*)
      - Diseño y análisis estadístico de experimentos
          - Análisis de varianza
          - Análisis de covarianza
          - Comparación de medias
      - Modelos lineales con R
          - Regresión lineal simple
          - Regresión lineal múltiple
      - Análisis multivariado con R
          - Análisis de componentes principales
          - Análisis de clúster
  - Todas las sesiones serán asistidas por la dirección del semillero
  - Cada sesión contará con actividades desarrolladas por los participantes
  
## Temas

- [Resumen tópicos 2019-01](/Actividades/Recordatorio.html)
    - [Archivo .Rmd](https://github.com/unal-semilleroR-FacCA/unal-semilleror-facca.github.io/blob/master/Actividades/Recordatorio.Rmd)
    - [Archivo .css](https://github.com/unal-semilleroR-FacCA/unal-semilleror-facca.github.io/blob/master/Actividades/estilo_p.css)
- [Ejercicio práctico 1](/Actividades/Ejercicio1.html)
    - [Archivo .Rmd](https://github.com/unal-semilleroR-FacCA/unal-semilleror-facca.github.io/blob/master/Actividades/Ejercicio1.Rmd)
    - [Solución tentativa](https://rpubs.com/Edimer/515789)
        - [Archivo .Rmd](https://github.com/unal-semilleroR-FacCA/unal-semilleror-facca.github.io/blob/master/Actividades/Actividad1_201902.Rmd)
        - [Bases de datos](/Actividades/Datos.7z)
- [Análisis de regresión]()
    - [Correlación: visualizaciones](/Actividades/CorRLS.html)
        - [Archivo .Rmd](https://github.com/unal-semilleroR-FacCA/unal-semilleror-facca.github.io/blob/master/Actividades/CorRLS.Rmd)
        - [Base de datos .csv](Actividades/Datos_Continentes.csv)
    - [Regresión Lineal Simple]()
        - [Regresión Lineal Simple: actividad]()
    - [Regresión Lineal Múltiple: ejemplo]()
- [Métodos Multivariados]()
    - [Análisis de Componentes Principales]()
        - [Ejemplo con datos del Banco Mundial]()
            - [Datos .csv]()
    - [Clusterización]()
        - [Medidas de similitud]()
        - [Ejemplo con datos del Banco Mundial]()
            - [Datos .csv](Actividades/Datos_Continentes.csv)
    - [Análisis de correspondencias]()
        - [Test $\chi^2$]()
        - [Ejemplo]()
            - [Datos .csv]()
- [Machine Learning: contexto]()
    - [Métodos de clasificación]()
        - [Regresión logística]()
        - [Árboles de decisión]()
- [Logo Semillero R]()
- [Propuestas Rday Medellín 2019]()
    - Encuesta: percepción de la deserción estudiantil
        - [Planificación de encuestas](Actividades/Encuestas.html)
        - [Banco de preguntas]()        
        - [Encuesta final: ficha técnica]()
        - [Datos .csv]()