---
title: "Integrantes"
---

| Nombre | Carrera | Institución |
| :----- | :-----: | :---------: |
| Alejandra Valencia | Zootecnia | Universidad Católica de Oriente |
| Alejandro Jaramillo Arango | Ingeniería Forestal |  Universidad Nacional |
| Andres Felipe Ramírez Peláez | Zootecnia | Universidad Nacional |
|Angela María Giraldo Duque | Ingeniería Agropecuaria | Universidad de Antioquia |
| Arledis Madera López | Ingeniería Agropecuaria | Universidad de Antioquia | 
| Camila F. Gutierrez Vergara | Zootecnia | Universidad Nacional |
| Cristian C. Gañan Tapasco | Ingeniería Forestal | Universidad Nacional |
| Cristian Rivera González | Ingeniería de Control | Universidad Nacional |
| Daniela Mejia Sierra | Ingeniería Agropecuaria | Universidad de Antioquia |
| Daniela Ortega González | Zootecnia | Universidad Nacional |
| Duván Ariel Nieves Ruiz | Ingeniería Ambiental | Universidad Nacional |
| Edgar Ruben Ortiz Suarez | Ingeniería Civil | Universidad Nacional |
| Edison Alexis Toro Sánchez | Ingeniería Forestal | Universidad Nacional |
| Elizabeth Burgos Ocampo | Zootecnia  | Universidad Nacional |
| Federico Loaiza Flórez | Ingeniería Forestal | Universidad Nacional |
| Federico Zapata | Zootecnia | Universidad Católica de Oriente |
| Haiver G. García Sánchez | Zootecnia | Universidad Nacional |
| Ingrid Zubany Ortiz Yepez | Ingeiería Forestal | Universidad Nacional |
| María C. Restrepo Quintero | Ingeniería Forestal | Universidad Nacional |
| María Isabel Mejia Quintero | Ingeniería Agropecuaria | Universidad de Antioquia |
| Mariana Angel Giraldo | Zootecnia | Universidad Nacional |
| Miguel Angel Pastor Dimate | Ingeniería Agronómica | Universidad Nacional |
| Natalia Andrea Marín Garzón | Zootecnia | Universidad Nacional |
| Ricardo Andres Velasco Daza | Zootecnia | Universidad Nacional |
| Santiago Quintero Guerrero | Zootecnia | Universidad Nacional |
| Sergio Nicolás Sánchez Sierra | Zootecnia | Universidad Nacional |
| Yudith A. Sánchez Balaguera | Zootecnia | Universidad Nacional |
| Yuliana Ramírez Gómez | Ingeniería Agropecuaria | Universidad de Antioquia |

