---
title: "Recursos de información"
---

## Sitios web

Algunos recursos de información en los cuales el usuario podrá encontrar múltiples
ayudas, ejemplos, tutoriales y ejercicios para desarrollar con `R` (y otros lenguajes de programación) son los siguientes:

- [Stack Overflow en inglés](https://stackoverflow.com/)
- [Stack Overflow en español](https://es.stackoverflow.com/)
- [Rpubs](https://rpubs.com/)
- [CRAN](https://cran.r-project.org/)
- [R-Studio](https://www.rstudio.com/)
- [DataCamp](https://www.datacamp.com/)
- [Github](https://github.com/)
- [edX](https://www.edx.org/es/course/subject/data-analysis-statistics)
- [R-Exercises](https://www.r-exercises.com/)
- [R-bloggers](https://www.r-bloggers.com/)

## Material bibliográfico

Además de los sitios web, también se recomienda al usuario tener en cuenta el siguiente material de apoyo:

- [R for Data Science - R4ds](http://r4ds.had.co.nz/)
- [*R: A Language for Data Analysis and Graphichs*](https://www.stat.auckland.ac.nz/~ihaka/downloads/R-paper.pdf)
- [*R and S*](http://vita.had.co.nz/papers/r-s.pdf)
- [*R for Beginners*](https://cran.r-project.org/doc/contrib/Paradis-rdebuts_en.pdf)
- [*R para principiantes*](https://cran.r-project.org/doc/contrib/rdebuts_es.pdf)
- [*An Introduction to R*](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf)
- [*Introduction to the R project for Statistical Computing for use at ITC*](https://cran.r-project.org/doc/contrib/Rossiter-RIntro-ITC.pdf)
- [*R for Biologists*](https://cran.r-project.org/doc/contrib/Martinez-RforBiologistv1.1.pdf)
- [*Métodos Estadísticos con R y R commander*](https://cran.r-project.org/doc/contrib/Saez-Castillo-RRCmdrv21.pdf)
- [*Statistics Using R with Biological Examples*](https://cran.r-project.org/doc/contrib/Seefeld_StatsRBio.pdf)
- [*OpenIntro Statistics*](https://www.openintro.org/download.php?file=os3_tablet)
- [*An Introduction to Statistical Learning with Applications in R*](http://www-bcf.usc.edu/~gareth/ISL/ISLR%20First%20Printing.pdf)
- [*Handbook of Biological Statistics*](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.471.3602&rep=rep1&type=pdf)
- [*Gráficos Estadísticos con R*](https://cran.r-project.org/doc/contrib/grafi3.pdf)
- [El arte de programar en R](https://cran.r-project.org/doc/contrib/Santana_El_arte_de_programar_en_R.pdf)
- [*Computational Statistics Using R and R Studio An Introduction for Scientists*](http://www.calvin.edu/~rpruim/talks/SC11/Seattle/RatSC11/Master-StatsForScience.pdf)

## Hojas de referencia

Las siguientes son guías de `R` y `R Studio` que pueden ser consultadas [aquí](https://www.rstudio.com/resources/cheatsheets/).

- Hojas de referencia en español:
  - [Importación de datos](/Actividades/2021_01/pdf/data-import-Spanish_translation-2019.pdf)
  - [Manejo de datos (1)](/Actividades/2021_01/pdf/data-transformation_Spanish.pdf)
  - [Manejo de datos (2)](/Actividades/2021_01/pdf/data-wrangling-cheatsheet_Spanish.pdf)
  - [Manejo de factores con `forcats`](/Actividades/2021_01/pdf/factors-Spanish.pdf)
  - [Maneo de fechas con `lubridate`](/Actividades/2021_01/pdf/lubridate-Spanish-translation-2019.pdf)
  - [Manejo de caracteres con `stringr`](/Actividades/2021_01/pdf/strings_Spanish.pdf)
  - [Visualización con `ggplot2`](/Actividades/2021_01/pdf/ggplot2.pdf)
  - [Programación con `purrr`](/Actividades/2021_01/pdf/purrr_COrtega_Spanish.pdf)
  - [Ecosistema R Markdown](/Actividades/2021_01/pdf/rmarkdown-2.0_Spanish.pdf)
  - [Aplicaciones con `shiny`](/Actividades/2021_01/pdf/shiny_Spanish.pdf)
  - [IDE RStudio](/Actividades/2021_01/pdf/rstudio-entorno.pdf)
- Hojas de referencia en inglés:
  - [*Base R: Cheat Sheet*](https://www.rstudio.com/wp-content/uploads/2016/05/base-r.pdf)
  - [*RStudio IDE Cheat Sheet*](https://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf)
  - [Data Visualization with ggplot2](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf)
  - [R Markdown](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)
  - [Shiny](https://www.rstudio.com/wp-content/uploads/2015/02/shiny-cheatsheet.pdf)