---
title: "R & RStudio"
---

## Lenguaje de programación R

`R` es un lenguaje de distribución libre (bajo la licencia [GPL - *General Public Licence*](https://en.wikipedia.org/wiki/GNU_General_Public_License)), interpretado y de gran uso en la manipulación de datos para el cómputo estadístico y gráfico. Disponible para Linux, MacOS y Windows. `R` fue creado por Ross Ihaka y Robert Gentleman a principios de los años 90 en Nueva Zelanda, y puede ser definido como una implementación del lenguaje `S`, este último desarrollado en AT&T por John Chambers, Rick Becker y Allan Wilks.

 John Chambers y Trevor Hastie en el año 1991 describen en el texto *Statistical Models in S:* 

> "Buscamos que los usuarios puedan iniciar en un entorno interactivo, en el que no se vean, conscientemente, a ellos mismos como programadores. Conforme sus necesidades sean más claras y su complejidd se incremente, deberían gradualmente poder profundizar en la programación, es cuando los aspectos del lenguaje y el sistema se vuelven más importantes".


## R-Studio

`R-Studio` es un entorno de desarrollo integrado (IDE) de fuente abierta para el lenguaje de programación `R`, que ofrece gran variedad de herramientas tecnológicas de vanguardia para la importación, administración, visualización, modelación y comunicación de la información. (Para más información consultar [RStudio](https://www.rstudio.com/)). 

## Aplicaciones

  - Bioinformática
      - Genómica
      - Detección de enfermedades
      - Clasificación de tumores
      - Búsqueda de patrones en secuencias de DNA o RNA
      - Algoritmos de [Machine Learning](https://en.wikipedia.org/wiki/Machine_learning) para clasificación de pacientes con determinadas patologías
  - Desarrollo de herramientas de software
      - Construcción de bibliotecas para R
      - Construcción de tableros de datos
      - Construcción de páginas web
      - Construcción de artículos científicos en formado PDF
      - Construcción de aplicaciones de datos
  - Agricultura de precisión    
  - Geoestadística 
      - SIG
      - Análisis de imagen
      - Cartografía digital
  - Simulación
  - Actuaría
  - Econometría financiera
  - Técnicas de pronóstico
  - Machine learning
  - Data mining
  - Web scraping
  - Big data
  - [Galería de R](https://www.r-graph-gallery.com/)
  - [Galería de RStudio](https://rmarkdown.rstudio.com/gallery.html)
  - [Galería de Shiny](https://shiny.rstudio.com/gallery/)
      