{
  "hash": "f36013fbba03c6d06a6141f300128d11",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Análisis de Regresión\"\nauthor: \"Semillero R - FacCA\"\ndate: \"17 de agosto de 2019\"\noutput:\n  ioslides_presentation:\n    css: estilo.css\n    df_print: paged\n    widescreen: true\n    smaller: true\n    logo: images/logo.png\n---\n\n\n\n\n# Problema\n\n## Descripción del problema\n<div class = \"black\">\n**Gasto militar vs Gasto en Educación:** previamente se evidenció a través de gráficos de dispersión y métricas de correlación, la relación negativa entre la inversión militar y la inversión en educación. Se sugiere construir un modelo de regresión lineal simple que permita determinar el cambio en $y$ dado $x$, es decir, que el modelo permitirá establecer por cada unidad que aumenta el gasto militar, cuánto disminuye el gasto en educación.\nEl modelo se puede expresar de la siguiente manera: \n<br>\n<br>\n<center>\n- Modelo matemático: $y = mx + b$\n- Modelo estadístico 1: $y = \\beta_0\\ +\\ \\beta_1X$\n- Modelo estadístico 2: $\\hat{y_i} = \\hat{\\beta_0}\\ + \\hat{\\beta_1}X_i\\ + \\epsilon_i$\n</center>\n</div>\n# Gasto Militar vs Gasto Educación\n\n## Base de datos\n<br>\n<br>\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n                               pais gasto_militar17 gasto_edu16\n1                        Afganistán    0.9068569412     4.20525\n2                           Albania    1.2441751239     3.95464\n3                         Argentina    0.9096629933     5.57218\n4                           Armenia    3.9680393674     2.75812\n5                        Azerbaiyán    3.9373999369     2.90341\n6                        Bangladesh    1.3807504138     1.53554\n7                           Belarús    1.1919853143     4.94655\n8                            Belice    1.2530838896     7.06045\n9                             Benin    1.2163217396     3.99469\n10                Brunei Darussalam    2.8792250162     4.42541\n11                          Burundi    1.9831535621     4.61813\n12                       Cabo Verde    0.5420811232     5.36651\n13                          Camerún    1.3165941862     2.68755\n14                            Chile    1.9100618544     5.35064\n15                         Colombia    3.1022327050     4.52091\n16 Congo, República Democrática del    0.6987735959     2.11869\n17                       Costa Rica    0.0000000000     7.11873\n18                    Côte d'Ivoire    1.2804434296     4.94837\n19                      El Salvador    0.9005176939     3.86991\n20                          Georgia    2.2251392292     3.78477\n21                            Ghana    0.4060350550     5.76632\n22                        Guatemala    0.3732213478     2.83281\n23                           Guinea    2.3324667356     2.51800\n24                           Guyana    1.4436772536     6.06100\n25                            Haití    0.0008874827     2.44959\n26                         Honduras    1.5782303116     6.30177\n27     Irán, República Islámica del    3.0992593495     3.36576\n28                          Jamaica    0.9035377847     5.31866\n29                            Japón    0.9349600138     3.46746\n30                         Jordania    4.7977879047     3.89621\n31                        Kazajstán    0.8412224616     2.97810\n32                            Kenya    1.2307076293     5.36267\n33                       Kirguistán    3.1581710557     6.58615\n34                          Liberia    0.6381542056     4.00885\n35                          Malasia    1.1254530523     4.82754\n36                           Malawi    0.7701815595     4.74857\n37                             Malí    3.0540937475     3.09071\n38                         Mauricio    0.1806502692     5.01360\n39                         Mongolia    0.7371034337     5.18212\n40                            Nepal    1.5527522697     4.44099\n41                        Nicaragua    0.6099226660     4.11264\n42                            Níger    2.6747584248     4.04160\n43                   Nueva Zelandia    1.1584442250     6.30374\n44                         Pakistán    3.4954831621     2.49180\n45                         Paraguay    1.1841593158     4.52037\n46                             Perú    0.9773833671     3.81827\n47                      Reino Unido    1.8348367707     5.54179\n48             República de Moldova    0.4206777465     6.66130\n49                           Rwanda    0.9745172897     3.53979\n50                          Senegal    1.8966349226     6.62561\n51                           Serbia    1.8285005701     3.86178\n52                       Seychelles    1.5655817347     4.41832\n53                     Sierra Leona    0.7233298489     3.06023\n54                        Sri Lanka    2.1719720294     3.47508\n55                        Sudáfrica    1.0474903232     5.94059\n56                            Suiza    0.6836302129     5.12430\n57                             Togo    1.9352608797     5.06326\n58                          Ucrania    3.4129745864     5.01437\n59                           Uganda    1.6750659682     2.55882\n```\n\n\n:::\n:::\n\n\n## Distribuciones\n\n<div class=\"columns-2\">\n#### Gasto militar\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](regsimple_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=480}\n:::\n:::\n\n<div class=\"columns-2\">\n#### Gasto Educación\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](regsimple_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=480}\n:::\n:::\n\n</div>\n\n## Gráficos de dispersión\n<div class=\"columns-2\">\n#### Con valor atípico\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](regsimple_files/figure-html/unnamed-chunk-4-1.png){fig-align='center' width=480}\n:::\n:::\n\n<div class=\"columns-2\">\n#### Sin valor atípico\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](regsimple_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=480}\n:::\n:::\n\n</div>\n\n# Correlación\n\n## Concepto\n<div class = \"black\">\nEl coeficiente de correlación de *Pearson* es una medida lineal entre dos variables aleatorias cuantitativas. A diferencia de la covarianza, la correlación es independiente de la escala de medida.\n\nEste coeficiente puede ser de dos tipos:\n\n- Paramétrico: sujeto a distribución normal o gausiana.\n- No paramétrico: no está sujeto a distribución normal o gausiana.\n<br>\n<br>\n$$\\rho_{(X,Y)} = \\frac{Cov_{(X,Y)}}{\\sigma_X\\times\\sigma_Y} = \\frac{\\sum_{i=1}^{n}(X_i-\\mu_X)(Y_i-\\mu_Y)}{\\sigma_X\\times\\sigma_Y}$$\n</div>\n## Interpretación de $\\rho$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/corr.jpg){fig-align='center' width=650px}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/measurecor.png){fig-align='center' width=650px}\n:::\n:::\n\n\n## Relaciones Lineales: análisis exploratorio\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![[Fuente: Wikipedia.](https://en.wikipedia.org/wiki/Anscombe%27s_quartet)](images/cor_ascombe.png){fig-align='center' width=650px}\n:::\n:::\n\n\n## Prueba de Hipótesis para $\\rho$\n<div class = \"columns-2\">\n<div class = \"black\">- **Correlación de Pearson con dato atípico:**</div>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.005680844\n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](regsimple_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n#### Test de hipótesis con valor atípico\n<div class = \"black\">\n$$H_0: \\rho = 0\\\\H_1: \\rho \\neq 0$$\n</div>\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  datos$gasto_militar17 and datos$gasto_edu16\nt = 0.043265, df = 58, p-value = 0.9656\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.2486025  0.2592316\nsample estimates:\n        cor \n0.005680844 \n```\n\n\n:::\n:::\n\n<div class = \"black\">\n**Conclusión:** como el valor p (0.9656) es mayor que el nivel de significancia $\\alpha = 0.05$, no existe evidencia para rechazar la hipótesis nula.</div>\n</div>\n## Prueba de Hipótesis para $\\rho$\n<div class = \"columns-2\">\n<div class = \"black\">- **Correlación de Pearson sin dato atípico:**</div>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.2046813\n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](regsimple_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=480}\n:::\n:::\n\n\n#### Test de hipótesis sin valor atípico\n<div class = \"black\">\n$$H_0: \\rho = 0\\\\H_1: \\rho \\neq 0$$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  df_reg$gasto_militar17 and df_reg$gasto_edu16\nt = -1.5787, df = 57, p-value = 0.1199\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.43781539  0.05424418\nsample estimates:\n       cor \n-0.2046813 \n```\n\n\n:::\n:::\n\n\n**Conclusión:** como el valor p (0.1199) es mayor que el nivel de significancia $\\alpha = 0.05$, no existe evidencia para rechazar la hipótesis nula.</div>\n</div>\n\n# Regresión Lineal Simple (RLS)\n\n## Origen: Francis Galton\n\n<div class = \"columns-2\">\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![[Revista Biometrika](https://academic.oup.com/biomet)](images/galton.jpg){fig-align='center' width=380px}\n:::\n:::\n\n<br>\n<br>\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/galtondatos.PNG){fig-align='center' width=550px}\n:::\n:::\n\n</div>\n\n## Idea intuitiva RLS\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/regression.gif){fig-align='center' width=550px}\n:::\n:::\n\n\n### Modelo tentativo\n<div class = \"black\">\nEl modelo tentativo se puede expresar de la siguiente manera:\n\n$$G.Edu = \\beta_0\\ +\\ \\beta_1G.Militar$$\n</div>\n## RLS: percepción geométrica\n<div class = \"columns-2\">\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/regressionLineal.PNG){fig-align='center' width=550px}\n:::\n:::\n\n<br>\n<br>\n<br>\n<br>\n<br>\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/regression3.gif){fig-align='center' width=600px}\n:::\n:::\n\n</div>\n\n## RLS: ajuste de parámetros\n\n<div class = \"columns-2\">\n<br>\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/regression5.gif){fig-align='center' width=550px}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/regression2.gif){fig-align='center' width=550px}\n:::\n:::\n\n</div>\n<div class = \"black\">\n$$f(x|\\mu,\\sigma^2) = \\frac{1}{\\sqrt{2\\pi\\sigma^2}}e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}$$\n</div>\n## RLS: función muestral\n<div class = \"columns-2\">\n<br>\n<br>\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/regmuestral.PNG){fig-align='center' width=500px height=380px}\n:::\n:::\n\n<br>\n<br>\n<br>\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/regression4.gif){fig-align='center' width=500px height=270px}\n:::\n:::\n\n</div>\n\n## Función matemática\n<div class = \"black\">\n$$Y_i = E(Y|X_i)\\ +\\ \\epsilon_i\\\\$$\n\nAsumiendo que $E(Y|X_i)$ es lineal en $X_i$:\n\n$$Y_i = E(Y|X_i)\\ +\\ \\epsilon_i\\\\\nY_i = \\beta_0 +\\ \\beta_1X_i\\ +\\ \\epsilon_i$$\n\nTomando el valor esperado (esperanza matemática) a ambos lados:\n\n$$E(Y_i|X_i)\\ =\\  E[E(Y|X_i)] + E(\\epsilon_i|X_i)\\\\\nE(Y_i|X_i)\\ =\\ E(Y|X_i)\\ +\\ E(\\epsilon_i|X_i)$$\n\nComo $E(Y_i|X_i)$ es igual a $E(Y|X_i)$, la ecuación anterior determina que $E(\\epsilon_i|X_i) = 0$. Este supuesto implica que la media condicional de $\\epsilon_i$ es cero.\n</div>\n\n## Parámetros $\\beta_0$ y $\\beta_1$\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](regsimple_files/figure-html/unnamed-chunk-24-1.png){fig-align='center' width=816}\n:::\n:::\n\n\n## [Mínimos Cuadrados](https://es.wikipedia.org/wiki/M%C3%ADnimos_cuadrados)\n\n<div class = \"black\">\n**El propósito principal del análisis de regresión es estimar la función de regresión poblacional con base en la función de regresión muestral:**\n\n$$Y_i = \\beta_0\\ +\\ \\beta_1X$$\n$$\\hat{Y_i} = \\hat{\\beta_0}\\ + \\hat{\\beta_1}X_i\\ + \\hat{\\epsilon_i}$$\n</div>\n\n<center>\n[![Clic](images/youtube.PNG){width=67%}](https://www.youtube.com/watch?v=k964_uNn3l0)\n</img>\n\n## Supuestos matemáticos\n<div class = \"black\">\n1. Linealidad en los parámetros.\n2. Valores de $X$ independientes del término residual $\\epsilon$.\n3. <rojo>Valor medio de los residuales igual a cero: $E(\\epsilon_i|X_i) = 0$.</rojo>\n4. <rojo>Homocedasticidad o varianza constante de los errores $\\epsilon_i$.</rojo>\n5. Independencia de los errores (autocorrelación): $cov(\\epsilon_i, \\epsilon_j)=0$.\n<br>\n<br>\n$$\\epsilon\\ \\overset{\\text{i.i.d.}}\\sim\\ N(\\mu = 0,\\ \\sigma^2 = 1)$$\n\n</div>\n\n## Normalidad de los residuos\n<div class = \"black\">\n$$E(\\epsilon_i|X_i)=0$$\n</div>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/normalidad.PNG){fig-align='center' width=580px}\n:::\n:::\n\n\n## Homocedasticidad\n<div class = \"black\">\n$$Var(\\epsilon_i) = E[\\epsilon_i-E(\\epsilon_i|X_i)]^2\\\\\n= E(\\epsilon_i^2|X_i) \\\\\n= E(\\epsilon_i^2)\\\\\n= \\sigma^2$$\n</div>\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/homocedasticidad.PNG){fig-align='center' width=570px}\n:::\n:::\n\n\n## ¿Heterocedasticidad?\n<br>\n<br>\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/heterocedasticidad.PNG){fig-align='center' width=630px}\n:::\n:::\n\n\n# Regresión Lineal con R\n\n## Función `lm()` - `summary()`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#<b>\nmod1 <- lm(gasto_edu16 ~ gasto_militar17, data = df_reg)\n#</b>\nresumen_modelo <- summary(mod1)\nresumen_modelo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = gasto_edu16 ~ gasto_militar17, data = df_reg)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.92035 -0.83829  0.02911  0.80882  2.58509 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       4.8092     0.3058  15.727   <2e-16 ***\ngasto_militar17  -0.2559     0.1621  -1.579     0.12    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.313 on 57 degrees of freedom\nMultiple R-squared:  0.04189,\tAdjusted R-squared:  0.02509 \nF-statistic: 2.492 on 1 and 57 DF,  p-value: 0.1199\n```\n\n\n:::\n:::\n\n\n## Graficando recta (estático)\n<div class = \"columns-2\">\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](regsimple_files/figure-html/unnamed-chunk-29-1.png){fig-align='center' width=432}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](regsimple_files/figure-html/unnamed-chunk-30-1.png){fig-align='center' width=384}\n:::\n:::\n\n</div>\n\n## Graficando recta (ggplotly)\n<div class = \"rows-2\">\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(plotly)\nggplotly(df_reg %>% \n  ggplot(data = ., aes(x = gasto_militar17, y = gasto_edu16)) + \n  geom_point() + theme_light() +\n  geom_smooth(method = \"lm\", se = FALSE,  color = \"forestgreen\", lwd = 1.2) +\n  labs(x = \"G. Militar (% del PIB)\",\n       y = \"G. Educación (% del PIB)\",\n       title = \"Modelo ajustado\\nggplot2\"))\n```\n:::\n\n<center>\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-3b83db10b775cdf62f08\" style=\"width:100%;height:361px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-3b83db10b775cdf62f08\">{\"x\":{\"data\":[{\"x\":[0.90685694121361504,1.2441751239073799,0.90966299326187705,3.96803936744534,3.93739993685592,1.3807504137660001,1.1919853143222501,1.25308388957315,1.21632173957962,2.87922501615293,1.9831535621498,0.54208112320360302,1.31659418620152,1.91006185435294,3.1022327049551199,0.69877359586280197,0,1.2804434295890399,0.90051769392969505,2.2251392292421701,0.40603505500835202,0.373221347790199,2.3324667356362099,1.4436772535861899,0.00088748270663517701,1.5782303116346299,3.0992593494528999,0.90353778470444901,0.93496001378115401,4.7977879047356096,0.84122246161847603,1.2307076293139401,3.1581710557468798,0.63815420560747704,1.1254530522653401,0.77018155951052503,3.0540937475447301,0.18065026922045199,0.73710343374309295,1.55275226969285,0.60992266600560896,2.6747584247602099,1.1584442249668701,3.4954831621461899,1.1841593158456001,0.97738336711741203,1.8348367707231801,0.42067774647435402,0.97451728966177498,1.8966349225578401,1.8285005701376,1.5655817347019301,0.72332984888969298,2.1719720294153202,1.04749032315992,0.68363021288655701,1.93526087973578,3.4129745863639398,1.6750659682249001],\"y\":[4.2052497863769496,3.95463991165161,5.5721797943115199,2.7581200599670401,2.90340995788574,1.53553998470306,4.9465498924255398,7.0604500770568803,3.99468994140625,4.4254097938537598,4.6181302070617702,5.3665099143981898,2.68755006790161,5.3506398200988796,4.5209097862243697,2.1186900138854998,7.1187300682067898,4.9483699798584002,3.8699100017547599,3.7847700119018599,5.7663202285766602,2.8328099250793501,2.5179998874664302,6.0609998703002903,2.4495899677276598,6.3017702102661097,3.3657600879669198,5.3186597824096697,3.4674599170684801,3.8962099552154501,2.97810006141663,5.36266994476318,6.5861501693725604,4.00885009765625,4.8275399208068803,4.7485699653625497,3.09070992469788,5.0135998725891104,5.1821198463439897,4.4409899711608896,4.1126399040222203,4.0416002273559597,6.3037400245666504,2.49180006980896,4.5203700065612802,3.81826996803284,5.5417900085449201,6.6613001823425302,3.5397899150848402,6.62560987472534,3.8617799282074001,4.4183201789856001,3.06023001670837,3.47508001327515,5.9405899047851598,5.1243000030517596,5.0632600784301802,5.0143699645996103,2.55882000923157],\"text\":[\"gasto_militar17: 0.9068569412<br />gasto_edu16: 4.20525\",\"gasto_militar17: 1.2441751239<br />gasto_edu16: 3.95464\",\"gasto_militar17: 0.9096629933<br />gasto_edu16: 5.57218\",\"gasto_militar17: 3.9680393674<br />gasto_edu16: 2.75812\",\"gasto_militar17: 3.9373999369<br />gasto_edu16: 2.90341\",\"gasto_militar17: 1.3807504138<br />gasto_edu16: 1.53554\",\"gasto_militar17: 1.1919853143<br />gasto_edu16: 4.94655\",\"gasto_militar17: 1.2530838896<br />gasto_edu16: 7.06045\",\"gasto_militar17: 1.2163217396<br />gasto_edu16: 3.99469\",\"gasto_militar17: 2.8792250162<br />gasto_edu16: 4.42541\",\"gasto_militar17: 1.9831535621<br />gasto_edu16: 4.61813\",\"gasto_militar17: 0.5420811232<br />gasto_edu16: 5.36651\",\"gasto_militar17: 1.3165941862<br />gasto_edu16: 2.68755\",\"gasto_militar17: 1.9100618544<br />gasto_edu16: 5.35064\",\"gasto_militar17: 3.1022327050<br />gasto_edu16: 4.52091\",\"gasto_militar17: 0.6987735959<br />gasto_edu16: 2.11869\",\"gasto_militar17: 0.0000000000<br />gasto_edu16: 7.11873\",\"gasto_militar17: 1.2804434296<br />gasto_edu16: 4.94837\",\"gasto_militar17: 0.9005176939<br />gasto_edu16: 3.86991\",\"gasto_militar17: 2.2251392292<br />gasto_edu16: 3.78477\",\"gasto_militar17: 0.4060350550<br />gasto_edu16: 5.76632\",\"gasto_militar17: 0.3732213478<br />gasto_edu16: 2.83281\",\"gasto_militar17: 2.3324667356<br />gasto_edu16: 2.51800\",\"gasto_militar17: 1.4436772536<br />gasto_edu16: 6.06100\",\"gasto_militar17: 0.0008874827<br />gasto_edu16: 2.44959\",\"gasto_militar17: 1.5782303116<br />gasto_edu16: 6.30177\",\"gasto_militar17: 3.0992593495<br />gasto_edu16: 3.36576\",\"gasto_militar17: 0.9035377847<br />gasto_edu16: 5.31866\",\"gasto_militar17: 0.9349600138<br />gasto_edu16: 3.46746\",\"gasto_militar17: 4.7977879047<br />gasto_edu16: 3.89621\",\"gasto_militar17: 0.8412224616<br />gasto_edu16: 2.97810\",\"gasto_militar17: 1.2307076293<br />gasto_edu16: 5.36267\",\"gasto_militar17: 3.1581710557<br />gasto_edu16: 6.58615\",\"gasto_militar17: 0.6381542056<br />gasto_edu16: 4.00885\",\"gasto_militar17: 1.1254530523<br />gasto_edu16: 4.82754\",\"gasto_militar17: 0.7701815595<br />gasto_edu16: 4.74857\",\"gasto_militar17: 3.0540937475<br />gasto_edu16: 3.09071\",\"gasto_militar17: 0.1806502692<br />gasto_edu16: 5.01360\",\"gasto_militar17: 0.7371034337<br />gasto_edu16: 5.18212\",\"gasto_militar17: 1.5527522697<br />gasto_edu16: 4.44099\",\"gasto_militar17: 0.6099226660<br />gasto_edu16: 4.11264\",\"gasto_militar17: 2.6747584248<br />gasto_edu16: 4.04160\",\"gasto_militar17: 1.1584442250<br />gasto_edu16: 6.30374\",\"gasto_militar17: 3.4954831621<br />gasto_edu16: 2.49180\",\"gasto_militar17: 1.1841593158<br />gasto_edu16: 4.52037\",\"gasto_militar17: 0.9773833671<br />gasto_edu16: 3.81827\",\"gasto_militar17: 1.8348367707<br />gasto_edu16: 5.54179\",\"gasto_militar17: 0.4206777465<br />gasto_edu16: 6.66130\",\"gasto_militar17: 0.9745172897<br />gasto_edu16: 3.53979\",\"gasto_militar17: 1.8966349226<br />gasto_edu16: 6.62561\",\"gasto_militar17: 1.8285005701<br />gasto_edu16: 3.86178\",\"gasto_militar17: 1.5655817347<br />gasto_edu16: 4.41832\",\"gasto_militar17: 0.7233298489<br />gasto_edu16: 3.06023\",\"gasto_militar17: 2.1719720294<br />gasto_edu16: 3.47508\",\"gasto_militar17: 1.0474903232<br />gasto_edu16: 5.94059\",\"gasto_militar17: 0.6836302129<br />gasto_edu16: 5.12430\",\"gasto_militar17: 1.9352608797<br />gasto_edu16: 5.06326\",\"gasto_militar17: 3.4129745864<br />gasto_edu16: 5.01437\",\"gasto_militar17: 1.6750659682<br />gasto_edu16: 2.55882\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,0,0,1)\",\"opacity\":1,\"size\":5.6692913385826778,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\"}},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null},{\"x\":[0,0.060731492465007718,0.12146298493001544,0.18219447739502315,0.24292596986003087,0.3036574623250386,0.36438895479004629,0.42512044725505405,0.48585193972006174,0.54658343218506944,0.60731492465007719,0.66804641711508495,0.72877790958009259,0.78950940204510034,0.85024089451010809,0.91097238697511573,0.97170387944012349,1.0324353719051311,1.0931668643701389,1.1538983568351466,1.2146298493001544,1.2753613417651621,1.3360928342301699,1.3968243266951774,1.4575558191601852,1.5182873116251929,1.5790188040902007,1.6397502965552084,1.7004817890202162,1.7612132814852237,1.8219447739502315,1.8826762664152392,1.943407758880247,2.0041392513452547,2.0648707438102623,2.1256022362752702,2.1863337287402778,2.2470652212052857,2.3077967136702933,2.3685282061353008,2.4292596986003088,2.4899911910653163,2.5507226835303243,2.6114541759953318,2.6721856684603398,2.7329171609253473,2.7936486533903548,2.8543801458553628,2.9151116383203703,2.9758431307853783,3.0365746232503859,3.0973061157153938,3.1580376081804014,3.2187691006454089,3.2795005931104169,3.3402320855754244,3.4009635780404324,3.4616950705054399,3.5224265629704474,3.5831580554354554,3.6438895479004629,3.7046210403654709,3.7653525328304784,3.8260840252954864,3.8868155177604939,3.9475470102255015,4.0082785026905094,4.0690099951555174,4.1297414876205245,4.1904729800855325,4.2512044725505405,4.3119359650155475,4.3726674574805555,4.4333989499455635,4.4941304424105715,4.5548619348755786,4.6155934273405865,4.6763249198055945,4.7370564122706016,4.7977879047356096],\"y\":[4.8092175679899309,4.793676706629288,4.778135845268646,4.7625949839080031,4.7470541225473601,4.7315132611867181,4.7159723998260752,4.7004315384654323,4.6848906771047893,4.6693498157441473,4.6538089543835044,4.6382680930228615,4.6227272316622194,4.6071863703015765,4.5916455089409336,4.5761046475802916,4.5605637862196486,4.5450229248590057,4.5294820634983628,4.5139412021377208,4.4984003407770778,4.4828594794164349,4.4673186180557929,4.45177775669515,4.436236895334507,4.420696033973865,4.4051551726132221,4.3896143112525792,4.3740734498919362,4.3585325885312942,4.3429917271706513,4.3274508658100084,4.3119100044493663,4.2963691430887234,4.2808282817280805,4.2652874203674376,4.2497465590067955,4.2342056976461526,4.2186648362855106,4.2031239749248677,4.1875831135642247,4.1720422522035818,4.1565013908429398,4.1409605294822969,4.1254196681216539,4.1098788067610119,4.094337945400369,4.0787970840397261,4.0632562226790832,4.0477153613184411,4.0321744999577982,4.0166336385971553,4.0010927772365132,3.9855519158758703,3.9700110545152274,3.9544701931545849,3.9389293317939424,3.9233884704332995,3.907847609072657,3.8923067477120146,3.8767658863513716,3.8612250249907292,3.8456841636300862,3.8301433022694438,3.8146024409088009,3.7990615795481584,3.7835207181875159,3.767979856826873,3.7524389954662305,3.736898134105588,3.7213572727449451,3.7058164113843026,3.6902755500236601,3.6747346886630172,3.6591938273023743,3.6436529659417323,3.6281121045810893,3.6125712432204464,3.5970303818598039,3.5814895204991615],\"text\":[\"gasto_militar17: 0.00000000<br />gasto_edu16: 4.809218\",\"gasto_militar17: 0.06073149<br />gasto_edu16: 4.793677\",\"gasto_militar17: 0.12146298<br />gasto_edu16: 4.778136\",\"gasto_militar17: 0.18219448<br />gasto_edu16: 4.762595\",\"gasto_militar17: 0.24292597<br />gasto_edu16: 4.747054\",\"gasto_militar17: 0.30365746<br />gasto_edu16: 4.731513\",\"gasto_militar17: 0.36438895<br />gasto_edu16: 4.715972\",\"gasto_militar17: 0.42512045<br />gasto_edu16: 4.700432\",\"gasto_militar17: 0.48585194<br />gasto_edu16: 4.684891\",\"gasto_militar17: 0.54658343<br />gasto_edu16: 4.669350\",\"gasto_militar17: 0.60731492<br />gasto_edu16: 4.653809\",\"gasto_militar17: 0.66804642<br />gasto_edu16: 4.638268\",\"gasto_militar17: 0.72877791<br />gasto_edu16: 4.622727\",\"gasto_militar17: 0.78950940<br />gasto_edu16: 4.607186\",\"gasto_militar17: 0.85024089<br />gasto_edu16: 4.591646\",\"gasto_militar17: 0.91097239<br />gasto_edu16: 4.576105\",\"gasto_militar17: 0.97170388<br />gasto_edu16: 4.560564\",\"gasto_militar17: 1.03243537<br />gasto_edu16: 4.545023\",\"gasto_militar17: 1.09316686<br />gasto_edu16: 4.529482\",\"gasto_militar17: 1.15389836<br />gasto_edu16: 4.513941\",\"gasto_militar17: 1.21462985<br />gasto_edu16: 4.498400\",\"gasto_militar17: 1.27536134<br />gasto_edu16: 4.482859\",\"gasto_militar17: 1.33609283<br />gasto_edu16: 4.467319\",\"gasto_militar17: 1.39682433<br />gasto_edu16: 4.451778\",\"gasto_militar17: 1.45755582<br />gasto_edu16: 4.436237\",\"gasto_militar17: 1.51828731<br />gasto_edu16: 4.420696\",\"gasto_militar17: 1.57901880<br />gasto_edu16: 4.405155\",\"gasto_militar17: 1.63975030<br />gasto_edu16: 4.389614\",\"gasto_militar17: 1.70048179<br />gasto_edu16: 4.374073\",\"gasto_militar17: 1.76121328<br />gasto_edu16: 4.358533\",\"gasto_militar17: 1.82194477<br />gasto_edu16: 4.342992\",\"gasto_militar17: 1.88267627<br />gasto_edu16: 4.327451\",\"gasto_militar17: 1.94340776<br />gasto_edu16: 4.311910\",\"gasto_militar17: 2.00413925<br />gasto_edu16: 4.296369\",\"gasto_militar17: 2.06487074<br />gasto_edu16: 4.280828\",\"gasto_militar17: 2.12560224<br />gasto_edu16: 4.265287\",\"gasto_militar17: 2.18633373<br />gasto_edu16: 4.249747\",\"gasto_militar17: 2.24706522<br />gasto_edu16: 4.234206\",\"gasto_militar17: 2.30779671<br />gasto_edu16: 4.218665\",\"gasto_militar17: 2.36852821<br />gasto_edu16: 4.203124\",\"gasto_militar17: 2.42925970<br />gasto_edu16: 4.187583\",\"gasto_militar17: 2.48999119<br />gasto_edu16: 4.172042\",\"gasto_militar17: 2.55072268<br />gasto_edu16: 4.156501\",\"gasto_militar17: 2.61145418<br />gasto_edu16: 4.140961\",\"gasto_militar17: 2.67218567<br />gasto_edu16: 4.125420\",\"gasto_militar17: 2.73291716<br />gasto_edu16: 4.109879\",\"gasto_militar17: 2.79364865<br />gasto_edu16: 4.094338\",\"gasto_militar17: 2.85438015<br />gasto_edu16: 4.078797\",\"gasto_militar17: 2.91511164<br />gasto_edu16: 4.063256\",\"gasto_militar17: 2.97584313<br />gasto_edu16: 4.047715\",\"gasto_militar17: 3.03657462<br />gasto_edu16: 4.032174\",\"gasto_militar17: 3.09730612<br />gasto_edu16: 4.016634\",\"gasto_militar17: 3.15803761<br />gasto_edu16: 4.001093\",\"gasto_militar17: 3.21876910<br />gasto_edu16: 3.985552\",\"gasto_militar17: 3.27950059<br />gasto_edu16: 3.970011\",\"gasto_militar17: 3.34023209<br />gasto_edu16: 3.954470\",\"gasto_militar17: 3.40096358<br />gasto_edu16: 3.938929\",\"gasto_militar17: 3.46169507<br />gasto_edu16: 3.923388\",\"gasto_militar17: 3.52242656<br />gasto_edu16: 3.907848\",\"gasto_militar17: 3.58315806<br />gasto_edu16: 3.892307\",\"gasto_militar17: 3.64388955<br />gasto_edu16: 3.876766\",\"gasto_militar17: 3.70462104<br />gasto_edu16: 3.861225\",\"gasto_militar17: 3.76535253<br />gasto_edu16: 3.845684\",\"gasto_militar17: 3.82608403<br />gasto_edu16: 3.830143\",\"gasto_militar17: 3.88681552<br />gasto_edu16: 3.814602\",\"gasto_militar17: 3.94754701<br />gasto_edu16: 3.799062\",\"gasto_militar17: 4.00827850<br />gasto_edu16: 3.783521\",\"gasto_militar17: 4.06901000<br />gasto_edu16: 3.767980\",\"gasto_militar17: 4.12974149<br />gasto_edu16: 3.752439\",\"gasto_militar17: 4.19047298<br />gasto_edu16: 3.736898\",\"gasto_militar17: 4.25120447<br />gasto_edu16: 3.721357\",\"gasto_militar17: 4.31193597<br />gasto_edu16: 3.705816\",\"gasto_militar17: 4.37266746<br />gasto_edu16: 3.690276\",\"gasto_militar17: 4.43339895<br />gasto_edu16: 3.674735\",\"gasto_militar17: 4.49413044<br />gasto_edu16: 3.659194\",\"gasto_militar17: 4.55486193<br />gasto_edu16: 3.643653\",\"gasto_militar17: 4.61559343<br />gasto_edu16: 3.628112\",\"gasto_militar17: 4.67632492<br />gasto_edu16: 3.612571\",\"gasto_militar17: 4.73705641<br />gasto_edu16: 3.597030\",\"gasto_militar17: 4.79778790<br />gasto_edu16: 3.581490\"],\"type\":\"scatter\",\"mode\":\"lines\",\"name\":\"fitted values\",\"line\":{\"width\":4.5354330708661417,\"color\":\"rgba(34,139,34,1)\",\"dash\":\"solid\"},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":46.678408349641231,\"r\":7.3059360730593621,\"b\":43.098499673842149,\"l\":31.415525114155255},\"plot_bgcolor\":\"rgba(255,255,255,1)\",\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"title\":{\"text\":\"Modelo ajustado<br />ggplot2\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":17.534246575342468},\"x\":0,\"xref\":\"paper\"},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-0.23988939523678049,5.0376772999723904],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\"],\"tickvals\":[0,1,2,3,4,5],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"G. Militar (% del PIB)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[1.2563804805278735,7.3978895723819766],\"tickmode\":\"array\",\"ticktext\":[\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"],\"tickvals\":[2,3,4,5,6,7],\"categoryorder\":\"array\",\"categoryarray\":[\"2\",\"3\",\"4\",\"5\",\"6\",\"7\"],\"nticks\":null,\"ticks\":\"outside\",\"tickcolor\":\"rgba(179,179,179,1)\",\"ticklen\":3.6529680365296811,\"tickwidth\":0.33208800332088001,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(222,222,222,1)\",\"gridwidth\":0.33208800332088001,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"G. Educación (% del PIB)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":\"transparent\",\"line\":{\"color\":\"rgba(179,179,179,1)\",\"width\":0.66417600664176002,\"linetype\":\"solid\"},\"yref\":\"paper\",\"xref\":\"paper\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":\"rgba(255,255,255,1)\",\"bordercolor\":\"transparent\",\"borderwidth\":1.8897637795275597,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"58a86c64261\":{\"x\":{},\"y\":{},\"type\":\"scatter\"},\"58a86e6915c5\":{\"x\":{},\"y\":{}}},\"cur_data\":\"58a86c64261\",\"visdat\":{\"58a86c64261\":[\"function (y) \",\"x\"],\"58a86e6915c5\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n</center>\n</div>\n\n## Graficando recta (plot_ly)\n<div class = \"rows-2\">\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(plotly)\ndf_reg %>% \n  plot_ly(x = ~gasto_militar17) %>% \n  add_markers(y = ~gasto_edu16) %>% \n  layout(title = \"Modelo ajustado\\nplotly\",\n         width = 600, height = 300,\n         xaxis = list(title = \"G. Militar (% del PIB)\"),\n         yaxis = list(title = \"G. Educación (% del PIB)\")) %>% \n  add_lines(x = ~gasto_militar17, y = fitted(mod1)) %>% \n  layout(showlegend = FALSE)\n```\n:::\n\n<center>\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-b5aa7fe21051279ae695\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-b5aa7fe21051279ae695\">{\"x\":{\"visdat\":{\"58a86c1b4e66\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"58a86c1b4e66\",\"attrs\":{\"58a86c1b4e66\":{\"x\":{},\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"y\":{},\"type\":\"scatter\",\"mode\":\"markers\",\"inherit\":true},\"58a86c1b4e66.1\":{\"x\":{},\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"y\":[4.5771577679535982,4.4908398643603711,4.5764397143691671,3.7938176958631029,3.8016581608942164,4.4558909843175281,4.5041949551424425,4.488560159276787,4.497967395179935,4.0724394157337782,4.3017392677655035,4.6705019323288663,4.4723082169184876,4.3204430415635562,4.0153729509827425,4.630405173711317,4.8092175679899292,4.4815590005530339,4.5787799471422197,4.2398164407295642,4.7053153874024618,4.7137122380956971,4.2123519107245704,4.4397883454095117,4.8089904659520251,4.4053569435797915,4.0161338166186811,4.578007122202111,4.5699663432601998,3.5814895204991606,4.5939532772761149,4.494286123588604,4.001058628724012,4.6459173487211363,4.5212202021546437,4.6121322609595934,4.0276914505419583,4.7629901384510394,4.6205967749334231,4.4118766370944202,4.653141647435727,4.1247613136609251,4.5127779390013893,3.9147422800217573,4.5061975859423411,4.5591104359558932,4.3396927347306793,4.7015684016330779,4.5598438497183258,4.323878920990472,4.3413141342856214,4.4085936461955519,4.6241213610082514,4.2534216404028431,4.5411704440332343,4.6342802837376444,4.3139947468814572,3.9358557795464861,4.3805772213507801],\"type\":\"scatter\",\"mode\":\"lines\",\"inherit\":true}},\"layout\":{\"width\":600,\"height\":300,\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"title\":\"Modelo ajustado<br />plotly\",\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"G. Militar (% del PIB)\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"title\":\"G. Educación (% del PIB)\"},\"showlegend\":false,\"hovermode\":\"closest\"},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[0.90685694121361504,1.2441751239073799,0.90966299326187705,3.96803936744534,3.93739993685592,1.3807504137660001,1.1919853143222501,1.25308388957315,1.21632173957962,2.87922501615293,1.9831535621498,0.54208112320360302,1.31659418620152,1.91006185435294,3.1022327049551199,0.69877359586280197,0,1.2804434295890399,0.90051769392969505,2.2251392292421701,0.40603505500835202,0.373221347790199,2.3324667356362099,1.4436772535861899,0.00088748270663517701,1.5782303116346299,3.0992593494528999,0.90353778470444901,0.93496001378115401,4.7977879047356096,0.84122246161847603,1.2307076293139401,3.1581710557468798,0.63815420560747704,1.1254530522653401,0.77018155951052503,3.0540937475447301,0.18065026922045199,0.73710343374309295,1.55275226969285,0.60992266600560896,2.6747584247602099,1.1584442249668701,3.4954831621461899,1.1841593158456001,0.97738336711741203,1.8348367707231801,0.42067774647435402,0.97451728966177498,1.8966349225578401,1.8285005701376,1.5655817347019301,0.72332984888969298,2.1719720294153202,1.04749032315992,0.68363021288655701,1.93526087973578,3.4129745863639398,1.6750659682249001],\"y\":[4.2052497863769496,3.95463991165161,5.5721797943115199,2.7581200599670401,2.90340995788574,1.53553998470306,4.9465498924255398,7.0604500770568803,3.99468994140625,4.4254097938537598,4.6181302070617702,5.3665099143981898,2.68755006790161,5.3506398200988796,4.5209097862243697,2.1186900138854998,7.1187300682067898,4.9483699798584002,3.8699100017547599,3.7847700119018599,5.7663202285766602,2.8328099250793501,2.5179998874664302,6.0609998703002903,2.4495899677276598,6.3017702102661097,3.3657600879669198,5.3186597824096697,3.4674599170684801,3.8962099552154501,2.97810006141663,5.36266994476318,6.5861501693725604,4.00885009765625,4.8275399208068803,4.7485699653625497,3.09070992469788,5.0135998725891104,5.1821198463439897,4.4409899711608896,4.1126399040222203,4.0416002273559597,6.3037400245666504,2.49180006980896,4.5203700065612802,3.81826996803284,5.5417900085449201,6.6613001823425302,3.5397899150848402,6.62560987472534,3.8617799282074001,4.4183201789856001,3.06023001670837,3.47508001327515,5.9405899047851598,5.1243000030517596,5.0632600784301802,5.0143699645996103,2.55882000923157],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null},{\"x\":[0,0.00088748270663517701,0.18065026922045199,0.373221347790199,0.40603505500835202,0.42067774647435402,0.54208112320360302,0.60992266600560896,0.63815420560747704,0.68363021288655701,0.69877359586280197,0.72332984888969298,0.73710343374309295,0.77018155951052503,0.84122246161847603,0.90051769392969505,0.90353778470444901,0.90685694121361504,0.90966299326187705,0.93496001378115401,0.97451728966177498,0.97738336711741203,1.04749032315992,1.1254530522653401,1.1584442249668701,1.1841593158456001,1.1919853143222501,1.21632173957962,1.2307076293139401,1.2441751239073799,1.25308388957315,1.2804434295890399,1.31659418620152,1.3807504137660001,1.4436772535861899,1.55275226969285,1.5655817347019301,1.5782303116346299,1.6750659682249001,1.8285005701376,1.8348367707231801,1.8966349225578401,1.91006185435294,1.93526087973578,1.9831535621498,2.1719720294153202,2.2251392292421701,2.3324667356362099,2.6747584247602099,2.87922501615293,3.0540937475447301,3.0992593494528999,3.1022327049551199,3.1581710557468798,3.4129745863639398,3.4954831621461899,3.93739993685592,3.96803936744534,4.7977879047356096],\"y\":[4.8092175679899292,4.8089904659520251,4.7629901384510394,4.7137122380956971,4.7053153874024618,4.7015684016330779,4.6705019323288663,4.653141647435727,4.6459173487211363,4.6342802837376444,4.630405173711317,4.6241213610082514,4.6205967749334231,4.6121322609595934,4.5939532772761149,4.5787799471422197,4.578007122202111,4.5771577679535982,4.5764397143691671,4.5699663432601998,4.5598438497183258,4.5591104359558932,4.5411704440332343,4.5212202021546437,4.5127779390013893,4.5061975859423411,4.5041949551424425,4.497967395179935,4.494286123588604,4.4908398643603711,4.488560159276787,4.4815590005530339,4.4723082169184876,4.4558909843175281,4.4397883454095117,4.4118766370944202,4.4085936461955519,4.4053569435797915,4.3805772213507801,4.3413141342856214,4.3396927347306793,4.323878920990472,4.3204430415635562,4.3139947468814572,4.3017392677655035,4.2534216404028431,4.2398164407295642,4.2123519107245704,4.1247613136609251,4.0724394157337782,4.0276914505419583,4.0161338166186811,4.0153729509827425,4.001058628724012,3.9358557795464861,3.9147422800217573,3.8016581608942164,3.7938176958631029,3.5814895204991606],\"type\":\"scatter\",\"mode\":\"lines\",\"marker\":{\"color\":\"rgba(255,127,14,1)\",\"line\":{\"color\":\"rgba(255,127,14,1)\"}},\"error_y\":{\"color\":\"rgba(255,127,14,1)\"},\"error_x\":{\"color\":\"rgba(255,127,14,1)\"},\"line\":{\"color\":\"rgba(255,127,14,1)\"},\"xaxis\":\"x\",\"yaxis\":\"y\",\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n</center>\n</div>\n\n## Diagnósticos del modelo\n\n- Análisis de residuales:\n    - **Residuales ordinarios:** `residuals()`\n    - **Residuales estandarizados:** `rstandard()`\n    - **Residuales estudentizados:** `rstudent()`\n    - **Tarea:** ¿Cuál es la diferencia entre los tipos de residuales? ¿Cuándo usar cada uno y por qué?\n    - [Leer.](http://dm.udc.es/asignaturas/estadistica2/sec7_3.html)\n    - [Residuales con R.](https://tarwi.lamolina.edu.pe/~clopez/Regresion/Capitulo_7.html)\n\n## Residuales ordinarios con R\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\n#<b>\nplot(mod1)\n```\n\n::: {.cell-output-display}\n![](regsimple_files/figure-html/unnamed-chunk-35-1.png){fig-align='center' width=864}\n:::\n\n```{.r .cell-code}\n#</b>\n```\n:::\n\n\n## Normalidad de residuales\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#<b>\nerrores <- mod1$residuals # Residuales del modelo\n#</b>\npar(mfrow = c(1, 2))\nhist(errores, main = \"Histograma de residuales\")\nabline(v = mean(errores), col = \"red\", lwd = 2)\nqqnorm(errores, main = \"Gráfico cuantil-cuantil\")\nqqline(errores, col = \"red\")\n```\n\n::: {.cell-output-display}\n![](regsimple_files/figure-html/unnamed-chunk-36-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n## Homocedasticidad de residuales\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n#<b>\npredichos <- mod1$fitted.values\n#</b>\nplot(predichos, errores, main = \"Residuales vs Predichos\")\nabline(lm(errores ~ predichos), col = \"red\", lty = 2)\nabline(h = 2, col = \"blue\", lty = 2)\nabline(h = -2, col = \"blue\", lty = 2)\n```\n\n::: {.cell-output-display}\n![](regsimple_files/figure-html/unnamed-chunk-37-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n## Medidas de influencia\n<div class = \"columns-2\">\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# <b>\nlibrary(car)\ninfluencePlot(mod1)\n```\n\n::: {.cell-output-display}\n![](regsimple_files/figure-html/unnamed-chunk-38-1.png){fig-align='center' width=480}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      StudRes        Hat       CookD\n4  -0.8312276 0.10496570 0.040736041\n6  -2.3284733 0.01746053 0.044706663\n25 -1.8881594 0.05415889 0.097674574\n30  0.2618339 0.17620806 0.007453931\n33  2.0838759 0.05565281 0.120870520\n```\n\n\n:::\n\n```{.r .cell-code}\n# </b>\n```\n:::\n\n</div>\n\n## Diagnósticos del modelo | Contraste de hipótesis (`lmtest`)\n<div class = \"columns-2\">\n<div class = \"black\">\n- **Shapiro Wilk - Normalidad:**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nshapiro.test(errores)\n## \n## \tShapiro-Wilk normality test\n## \n## data:  errores\n## W = 0.98764, p-value = 0.8122\n```\n:::\n\n\n- **Breusch Pagan - Homocedasticidad:**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# <b>\nlibrary(lmtest)\n# </b>\nbptest(mod1)\n## \n## \tstudentized Breusch-Pagan test\n## \n## data:  mod1\n## BP = 1.2889, df = 1, p-value = 0.2563\n```\n:::\n\n<br>\n<br>\n<br>\n- **Durbin-Watson - Autocorrelación:**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndwtest(mod1, order.by = NULL)\n## \n## \tDurbin-Watson test\n## \n## data:  mod1\n## DW = 2.5595, p-value = 0.9863\n## alternative hypothesis: true autocorrelation is greater than 0\n```\n:::\n\n\n- **Harvey/Collier - Linealidad:**\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nharvtest(mod1, order.by = NULL)\n## \n## \tHarvey-Collier test\n## \n## data:  mod1\n## HC = 0.82571, df = 56, p-value = 0.4125\n```\n:::\n\n</div>\n</div>\n## Bondad de ajuste del modelo (R^2^)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nresumen_modelo$adj.r.squared\n## [1] 0.02508557\n\nresumen_modelo$r.squared\n## [1] 0.04189444\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/ascombe.PNG){fig-align='center' width=650px height=400px}\n:::\n:::\n\n\n## Modelo final\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggpmisc)\nggplot(data = df_reg, aes(x = gasto_militar17, y = gasto_edu16)) + \n  geom_point() + theme_light() +\n  geom_smooth(method = \"lm\", se = TRUE,  color = \"firebrick\", lwd = 1.2) +\n  labs(x = \"G. Militar (% del PIB)\", y = \"G. Educación (% del PIB)\",\n       title = \"Modelo final de RLS\") +\n  stat_poly_eq(aes(label =  paste(..eq.label.., ..adj.rr.label.., sep = \"~~~~\")),\n               formula = y ~ x, parse = TRUE, label.x.npc = 0.9, color=\"black\")\n```\n\n::: {.cell-output-display}\n![](regsimple_files/figure-html/unnamed-chunk-45-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n## Intervalos de confianza de $\\beta_0$ y $\\beta_1$\n<div class = \"black\">\n- Función `confint()`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# <b>\nconfint(mod1, level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     2.5 %   97.5 %\n(Intercept)      4.1968927 5.421542\ngasto_militar17 -0.5804712 0.068682\n```\n\n\n:::\n\n```{.r .cell-code}\n#</b>\n```\n:::\n\n</div>\n## Estimaciones y Predicciones\n<div class = \"black\">\n- Función `predict()`\n- **Estimación:** estimar cúal es el gasto <rojo>promedio</rojo> en educación para un país que tiene 2.15% del PIB en inversión militar.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npredict(object = mod1, newdata = data.frame(gasto_militar17 = c(2.1)),\n        interval = \"confidence\", level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 4.271839 3.887763 4.655915\n```\n\n\n:::\n:::\n\n\n- **Predicción:** predecir cúal es el gasto en educación para un país que tiene 2.15% del PIB en inversión militar.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npredict(object = mod1, newdata = data.frame(gasto_militar17 = c(2.1)),\n        interval = \"prediction\", level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       fit      lwr      upr\n1 4.271839 1.613811 6.929867\n```\n\n\n:::\n:::\n\n</div>\n## ¿Regresión Lineal Múltiple?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](images/rlm.gif){fig-align='center' width=600px}\n:::\n:::\n",
    "supporting": [
      "regsimple_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../site_libs/plotly-binding-4.10.4/plotly.js\"></script>\n<script src=\"../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../site_libs/jquery-3.5.1/jquery.min.js\"></script>\n<link href=\"../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n<link href=\"../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}